### PR TITLE
Fixing build with latest OSX and Xcode 7.

### PR DESCRIPTION
**Pull request by TheIndifferent**
Unfortunately the build system of `jdk9` went too far ahead, I doubt that backporting it to `jdk8u` is viable. This pull request makes it possible to build the project on current version of OSX (10.11.5) and Xcode (7.3.1), only using single additional make varialbe:
`make COMPILER_WARNINGS_FATAL=false images`

### CODE REVIEW

**Comment by forantar** [comment]
Hi, thanks for participating! I've tried your patch (along with the hotspot part). Building with Xcode 7.0.1 was a success, but it failed with Xcode 4.6.3...

Having the option to compile with Xcode/clang would probably be fine. However, we're still better to align the toolchain with OpenJDK 8. So the changes should allow for a fallback to Xcode/gcc.

Have you tried to back port https://bugs.openjdk.java.net/browse/JDK-8019470?

**Comment by TheIndifferent** [comment]
Thanx for trying it. I was trying to backport changes from jdk9, but its completely different. Will try to cherry-pick the changes, and build them on both 4.6 and 7.0.

PS: are there any public mailing lists or discussion forums where you are discussing the development or your OpenJDK fork? I was trying to do the same on my own in https://github.com/tuxjdk/tuxjdk project, but yours is much better, so I would rather help you where possible.

**Comment by bulenkov** [comment]
Hello Stanislav. We're thinking about a public channel on Slack. We'll let you know as soon as we open it.

**Comment by TheIndifferent** [comment]
Sorry to bother you again with this, I've tried to use Xcode 4.6.3 for the build, it passed and able to start the IDE. Could you please post the error you're seeing?

**Comment by forantar** [comment]
Well, I've tried that again and indeed I was able to build with both the Xcode versions. So, likely I did something wrong the first time, sorry about that.

I've created a review for your changes: https://upsource.jetbrains.com/jetbrains-runtime/review/JR-CR-24
Are you seeing it?

**Comment by TheIndifferent** [comment]
Yes, I can see it, thank you very much. Of course would be mazing to have more eyes on that pull request, target audience is quite wide :)

In future, should I submit pull requests directly to https://upsource.jetbrains.com/jetbrains-runtime/view to simplify the process?

**Comment by forantar** [comment]
Great.
No, that's ok to file pull requests via github.

**Comment by avu** [comment]
@TheIndifferent Could you provide some info on my comments https://upsource.jetbrains.com/jetbrains-runtime/review/JR-CR-24?filePath=/hotspot/make/bsd/makefiles/gcc.make

Also, looks like it's more convenient to have a discussion concerning the fix here

**Comment by TheIndifferent** [comment]
@avu that's one of the reasons I wanted more eyes on that pull request. I am not sure how backward compatible is the change, so I cannot defend it.

Some googling through openjdk mailing lists gives the idea that flag is needed to make incremental build work on older compiler, so should be comparatively safe change unless you are actually using really old compiler and incremental builds.

**Comment by avu** [comment]
OK, let's use the fix here

**Pull request merged**
